#!/usr/bin/env python3
"""Generate the JSON5 identifier-name table from the UCD.

Reads ``third_party/ucd/<version>/DerivedCoreProperties.txt`` and writes
``src/json/tables/json5_ident_tables.c``. The output is committed, because a
build must need neither the network nor Python; this script is run by a person
when the pinned UCD version changes, and by ``make check-json5-tables`` to
prove that what is committed is what this script produces.

What is derived, and why from here. JSON5 says an unquoted object name is an
ECMAScript ``IdentifierName``, and ECMAScript defines that over the Unicode
properties ID_Start and ID_Continue. DerivedCoreProperties.txt is where those
two properties are published, so this reads them rather than a rendering of
them.

One table, not two. ID_Continue is a superset of ID_Start - the generator
asserts it rather than assuming it - so a single table carries both: a
codepoint's value says START (which also continues) or CONT_ONLY. A codepoint
no range mentions is in neither.

What is *not* in the table, and is in the lexer instead: ``$`` in either
position, which has neither property (it is Sc), and ``_`` as a *start*, which
is Pc and so carries ID_Continue but not ID_Start. Those two are ECMAScript's
own additions rather than Unicode properties, and two codepoints spelled out
in code read better than two one-element ranges here.

ZWNJ and ZWJ are deliberately *not* in that list: ECMAScript names them as
additions to IdentifierPart, but U+200C..U+200D carry ID_Continue in the UCD
this reads, so the table already admits them in continuation. Adding them
again would be a second spelling of the same rule that could drift from it.

Determinism is a requirement, not a nicety: the check target diffs the
regenerated output against the committed file, so the table is emitted from
sorted input in a fixed format with no timestamps and no dict-ordering
dependence.

Usage:
    tools/json5/gen_ident_tables.py [--ucd DIR] [--out DIR] [--version V]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import os
import sys

MAX_CODEPOINT = 0x10FFFF

START = 1
CONT_ONLY = 2

LICENSE_HEADER = """/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Text.
 *
 * Ghoti.io Text is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Text is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
"""


def parse_property(path, wanted):
    """Every codepoint carrying `wanted` in a UCD property file."""
    out = set()
    seen = False
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [p.strip() for p in line.split(";")]
            if len(fields) < 2 or fields[1] != wanted:
                continue
            seen = True
            rng = fields[0]
            if ".." in rng:
                lo, hi = rng.split("..")
                out.update(range(int(lo, 16), int(hi, 16) + 1))
            else:
                out.add(int(rng, 16))
    if not seen:
        raise SystemExit("no %s lines in %s" % (wanted, path))
    return out


def to_ranges(values):
    """A sorted {cp: value} mapping collapsed into runs sharing a value."""
    ranges = []
    for cp in sorted(values):
        v = values[cp]
        if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == v:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, v])
    return ranges


def emit(ranges, ucd_version, out_dir):
    names = {START: "GTEXT_JSON5_IDENT_START", CONT_ONLY: "GTEXT_JSON5_IDENT_CONT"}
    lines = []
    lines.append(LICENSE_HEADER)
    lines.append("""
/**
 * @file
 *
 * GENERATED by tools/json5/gen_ident_tables.py from UCD %s. Do not edit.
 *
 * Regenerate with:  tools/json5/gen_ident_tables.py
 * Verify with:      make check-json5-tables
 */

#include "json5_tables_internal.h"

const GTEXT_JSON5_Ident_Range gtext_json5_ident[] = {""" % ucd_version)

    cells = ["{0x%04X,0x%04X,%s}," % (lo, hi, names[v]) for lo, hi, v in ranges]
    # Two per line, as the IDNA tables are emitted, so a diff is readable.
    for i in range(0, len(cells), 2):
        lines.append("  " + " ".join(cells[i:i + 2]))
    lines.append("};")
    lines.append("")
    lines.append("const size_t gtext_json5_ident_count =")
    lines.append("    sizeof(gtext_json5_ident) / sizeof(gtext_json5_ident[0]);")
    lines.append("")

    path = os.path.join(out_dir, "json5_ident_tables.c")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path, len(ranges)


def main():
    here = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    version_file = os.path.join(here, "tools", "idna", "UCD_VERSION")
    default_version = "17.0.0"
    if os.path.exists(version_file):
        with open(version_file, "r", encoding="utf-8") as f:
            default_version = f.read().strip()

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--version", default=default_version,
                    help="UCD version (default: %s, from tools/idna/UCD_VERSION)" % default_version)
    ap.add_argument("--ucd", default=None, help="UCD directory")
    ap.add_argument("--out", default=os.path.join(here, "src", "json", "tables"),
                    help="output directory")
    args = ap.parse_args()

    ucd = args.ucd or os.path.join(here, "third_party", "ucd", args.version)
    dcp = os.path.join(ucd, "DerivedCoreProperties.txt")
    if not os.path.exists(dcp):
        raise SystemExit("no %s; run tools/idna/fetch.sh" % dcp)

    id_start = parse_property(dcp, "ID_Start")
    id_continue = parse_property(dcp, "ID_Continue")

    # ECMAScript's IdentifierPart is built on ID_Continue and its
    # IdentifierStart on ID_Start; a start that did not continue would make
    # the one-table encoding lossy, so it is checked rather than assumed.
    stray = id_start - id_continue
    if stray:
        raise SystemExit("ID_Start is not a subset of ID_Continue: %s" %
                         ", ".join("U+%04X" % cp for cp in sorted(stray)[:8]))

    values = {}
    for cp in id_continue:
        if cp > MAX_CODEPOINT:
            raise SystemExit("codepoint out of range: U+%04X" % cp)
        values[cp] = START if cp in id_start else CONT_ONLY

    ranges = to_ranges(values)
    if not os.path.isdir(args.out):
        os.makedirs(args.out)
    path, count = emit(ranges, args.version, args.out)
    sys.stderr.write("wrote %s: %d ranges (%d ID_Start, %d ID_Continue)\n"
                     % (path, count, len(id_start), len(id_continue)))


if __name__ == "__main__":
    main()
