/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Text.
 *
 * Ghoti.io Text is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Text is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */


/**
 * @file
 *
 * GENERATED by tools/json5/gen_ident_tables.py from UCD 17.0.0. Do not edit.
 *
 * Regenerate with:  tools/json5/gen_ident_tables.py
 * Verify with:      make check-json5-tables
 */

#include "json5_tables_internal.h"

const GTEXT_JSON5_Space_Range gtext_json5_space[] = {
  {0x0020,0x0020}, {0x00A0,0x00A0},
  {0x1680,0x1680}, {0x2000,0x200A},
  {0x202F,0x202F}, {0x205F,0x205F},
  {0x3000,0x3000},
};

const size_t gtext_json5_space_count =
    sizeof(gtext_json5_space) / sizeof(gtext_json5_space[0]);
