#!/usr/bin/env python3
"""Turn the published 2020-12 meta-schemas into a C file the library embeds.

The documents are fetched by tools/metaschema/fetch.sh into
third_party/json-schema/2020-12/ and are not committed; the file this writes
is, so that a build needs neither the network nor Python. `make
check-metaschema` regenerates into a temporary directory and diffs, which is
what stops the committed copy from drifting away from what is published.

The bytes are embedded verbatim - indentation, key order and all. Nothing here
reformats or minifies them. A normalised copy would be a different document
that happens to mean the same thing, and then the diff gate would be checking
this script's idea of the meta-schema rather than the published one.

Usage:  tools/metaschema/gen_metaschema.py [--ucd DIR] [--out DIR]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import json
import os
import sys

BASE = "https://json-schema.org/draft/2020-12"

# The order the file lists them in: the root first, then the vocabulary
# meta-schemas in the order the root's `allOf` references them, then
# format-assertion, which the root does not reference because the vocabulary
# it describes is the optional one.
DOCUMENTS = [
    ("schema.json", BASE + "/schema"),
    ("meta/core.json", BASE + "/meta/core"),
    ("meta/applicator.json", BASE + "/meta/applicator"),
    ("meta/unevaluated.json", BASE + "/meta/unevaluated"),
    ("meta/validation.json", BASE + "/meta/validation"),
    ("meta/meta-data.json", BASE + "/meta/meta-data"),
    ("meta/format-annotation.json", BASE + "/meta/format-annotation"),
    ("meta/format-assertion.json", BASE + "/meta/format-assertion"),
    ("meta/content.json", BASE + "/meta/content"),
]


def c_identifier(uri):
    """`.../meta/meta-data` -> `meta_meta_data`."""
    tail = uri[len(BASE) + 1:]
    return tail.replace("/", "_").replace("-", "_")


def c_string(chunk):
    """One C string literal for one line of the source document."""
    out = []
    for byte in chunk:
        ch = chr(byte)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif 0x20 <= byte < 0x7F:
            out.append(ch)
        else:
            # Should not arise - every published document is printable ASCII -
            # but an octal escape is correct rather than clever if one day one
            # is not, and `\xNN` would swallow a following hex digit.
            out.append("\\%03o" % byte)
    return '"' + "".join(out) + '"'


def load(directory, relative, uri):
    path = os.path.join(directory, relative)
    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        sys.exit("%s: %s\nrun tools/metaschema/fetch.sh first" % (path, exc))

    if not raw:
        sys.exit("%s is empty" % path)
    if any(byte >= 0x80 for byte in raw):
        sys.exit("%s is not ASCII; the embedding assumes it is" % path)
    if b"\r" in raw:
        sys.exit("%s has CRLF line endings; refetch it" % path)

    # The fetch could have been answered with the wrong document, or with a
    # page about the document. Both parse as something; only the right one
    # calls itself by the URI it was asked for.
    try:
        parsed = json.loads(raw.decode("ascii"))
    except ValueError as exc:
        sys.exit("%s is not JSON: %s" % (path, exc))
    if not isinstance(parsed, dict):
        sys.exit("%s is not a JSON object" % path)
    if parsed.get("$id") != uri:
        sys.exit("%s has $id %r, expected %r" % (path, parsed.get("$id"), uri))

    return raw


def emit(handle, documents):
    handle.write(
        "/**\n"
        " * @file\n"
        " *\n"
        " * The published JSON Schema 2020-12 meta-schemas, verbatim.\n"
        " *\n"
        " * GENERATED by tools/metaschema/gen_metaschema.py from the documents\n"
        " * tools/metaschema/fetch.sh retrieves. Do not edit: `make\n"
        " * check-metaschema` regenerates this file and fails on a difference.\n"
        " *\n"
        " * These are somebody else's documents and are reproduced unchanged,\n"
        " * under the terms they are published with. They are embedded rather\n"
        " * than fetched because the alternative is a validator that opens a\n"
        " * connection during a compile, to a URI taken from the document it was\n"
        " * asked to compile.\n"
        " *\n"
        " * Copyright 2026 by Corey Pennycuff\n"
        " */\n"
        "\n"
        "#include \"metaschema_internal.h\"\n")

    for _, uri, raw in documents:
        name = c_identifier(uri)
        handle.write("\n/* %s */\n" % uri)
        handle.write("static const char metaschema_%s[] =\n" % name)
        lines = raw.splitlines(True)
        for index, line in enumerate(lines):
            terminator = ";" if index + 1 == len(lines) else ""
            handle.write("    %s%s\n" % (c_string(line), terminator))

    handle.write("\nconst json_metaschema_doc json_metaschema_docs[] = {\n")
    for _, uri, _raw in documents:
        name = c_identifier(uri)
        handle.write("    {\"%s\",\n" % uri)
        handle.write("        metaschema_%s,\n" % name)
        handle.write("        sizeof(metaschema_%s) - 1},\n" % name)
    handle.write("};\n\n")
    handle.write("const size_t json_metaschema_doc_count =\n"
                 "    sizeof(json_metaschema_docs)"
                 " / sizeof(json_metaschema_docs[0]);\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(os.path.dirname(here))

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--documents",
        default=os.path.join(root, "third_party", "json-schema", "2020-12"),
        help="where fetch.sh put the published documents")
    parser.add_argument(
        "--out",
        default=os.path.join(root, "src", "json", "metaschema"),
        help="directory to write metaschema_docs.c into")
    args = parser.parse_args()

    documents = [
        (relative, uri, load(args.documents, relative, uri))
        for relative, uri in DOCUMENTS
    ]

    os.makedirs(args.out, exist_ok=True)
    target = os.path.join(args.out, "metaschema_docs.c")
    with open(target, "w", encoding="ascii", newline="\n") as handle:
        emit(handle, documents)

    total = sum(len(raw) for _, _, raw in documents)
    print("wrote %s: %d documents, %d bytes of JSON"
          % (target, len(documents), total))


if __name__ == "__main__":
    main()
